---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-server-deployment
spec:
  selector:
    matchLabels:
      app: code-server
  replicas: 1
  template:
    metadata:
      labels:
        app: code-server
    spec:
      containers:
      - name: code-server
        image: lscr.io/linuxserver/code-server:latest
        resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
        volumeMounts:
        - name: code-server
          mountPath: /config
      volumes:
      - name: code-server
        persistentVolumeClaim:
          claimName: code-server
---
apiVersion: v1
kind: Service
metadata:
  name: code-server-service
spec:
  type: NodePort
  # Uncomment the below line to create a Headless Service
  # clusterIP: None
  selector:
    app: code-server
  ports:
    - port: 8443
      nodePort: 30001
      name: http