---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: heimdall-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/heimdall"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: heimdall-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: heimdall-deployment
spec:
  selector:
    matchLabels:
      app: heimdall
  replicas: 1
  template:
    metadata:
      labels:
        app: heimdall
    spec:
      containers:
      - name: heimdall
        image: lscr.io/linuxserver/heimdall:latest
        resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
        volumeMounts:
        - mountPath: "/config"
          name: heimdall-storage
      volumes:
      - name: heimdall-storage
        persistentVolumeClaim:
          claimName: heimdall-claim
---
apiVersion: v1
kind: Service
metadata:
  name: heimdall-service
spec:
  type: NodePort
  # Uncomment the below line to create a Headless Service
  # clusterIP: None
  selector:
    app: heimdall
  ports:
    - port: 80
      nodePort: 30000
      name: http