---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: heimdall-deployment
spec:
  selector:
    matchLabels:
      app: heimdall
  replicas: 3
  template:
    metadata:
      labels:
        app: heimdall
    spec:
      containers:
      - name: heimdall
        image: lscr.io/linuxserver/heimdall:latest
        resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: heimdall-service
spec:
  type: NodePort
  # Uncomment the below line to create a Headless Service
  # clusterIP: None
  selector:
    app: heimdall
  ports:
    - port: 80
      nodePort: 30000
      name: http